services:
  api:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    networks:
      - my_network

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "54320:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: